name: CI

on:
  push:
    branches:
      - main
    tags: 
      - '*'
  pull_request:
    branches:
      - main
  release:
    types:
      - published

  schedule:
    - cron: '0 0-12 * * 1-5'
    - cron: '0 18 * * 0-4'

  workflow_dispatch:
    inputs:
      source_version:
        required: false
      test:
        required: true
        default: "hoge"
        type: choice
        options:
          - "hoge"
          - "fuga"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check inputs
        env:
          TEST: ${{ github.event.inputs.test }}
        run: echo ${TEST}

      - name: check inputs2
        env:
          TEST: ${{ github.event.inputs.test }}
        run: if [ "" = " ${TEST}" ]; then echo "true"; else echo "false"; fi

      - name: install jq
        run: sudo apt update -qqq && sudo apt install -qqqy --no-install-recommends jq

      - name: events
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: echo ${EVENT} | jq .

      - name: github
        env:
          GITHUB: ${{ toJSON(github) }}
        run: echo ${GITHUB} | jq .

      - name: env
        env:
          ENV: ${{ toJSON(env) }}
        run: echo ${ENV} | jq .

      - name: on pull request
        if: github.event_name == 'pull_request'
        run: echo pr/${{ github.event.pull_request.number }}

      - name: on push
        if: github.event_name == 'push'
        run: |
          ref=${{ github.ref }}
          echo ${ref##*/}

      - name: inline check
        run: |
          if [ -z ${{ github.base_ref }} ]; then
            ref=${{ github.ref }}
            echo ${ref##*/}
          else
            echo pr/${{ github.event.pull_request.number }}
          fi
          echo "event: ${{ github.event_name }}"

      - name: optionally inputs
        run: echo ${{ github.event.inputs.source_version }}
