name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule:
  #   - cron:  '5 * * * *'
  #   # - cron:  '*/10 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install jq
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqy --no-install-recommends jq

      - name: events
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: echo ${EVENT} | jq .

      - name: github
        env:
          GITHUB: ${{ toJSON(github) }}
        run: echo ${GITHUB} | jq .

      - name: env
        env:
          ENV: ${{ toJSON(env) }}
        run: echo ${ENV} | jq .

      - name: on pull request
        if: github.event_name == 'pull_request'
        run: echo pr/${{ github.event.pull_request.number }}

      - name: on push
        if: github.event_name == 'push'
        run: |
          ref=${{ github.ref }}
          echo ${ref##*/}

      - name: inline check
        run: |
          if [ -z ${{ github.base_ref }} ]; then
            ref=${{ github.ref }}
            echo ${ref##*/}
          else
            echo pr/${{ github.event.pull_request.number }}
          fi
          echo "event: ${{ github.event_name }}"

  mac-docker:
    runs-on: macos-11

    timeout-minutes: 20
    defaults:
      run:
        shell: bash --noprofile --norc -exo pipefail {0}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup docker
        uses: docker-practice/actions-setup-docker@v1
      
      - name: Test
        run: |
          # set -x
          docker version
          cat /etc/docker/daemon.json || true
          cat /Users/runner/.docker/daemon.json || true
          docker buildx version || true
          docker buildx ls || true

      - name: Docker build
        run: |
          docker build --rm -it --name hello .
      
      - name: Test run
        run: docker run --rm -it hello "Hello! world."
